Fix creating a new user checks if InitialSetup is needed.
origam/origam pull request #1301
Opened 2023-01-27 12:21 UTC by JiriPrajz

2023-01-27 17:30 UTC, JindrichSusen requested changes

2023-01-27 17:30 UTC, JindrichSusen commented on backend/Origam.Server/Configuration/IdentityGuiConfig.cs
>      }
I don't think it is a good idea to add to the configuration something that is not read from the config file. Could you use the UserTools.IsInitialSetupNeeded method directly?

2023-01-30 11:40 UTC, JindrichSusen approved these changes

2023-01-31 13:36 UTC, washibana approved these changes

2023-01-31 13:36 UTC, merged