Search with slash
origam/origam pull request #138
Opened 2022-01-11 15:14 UTC by JindrichSusen

2022-01-11 16:11 UTC, tvavrda commented on backend/Origam.ServerCore/Controller/SearchController.cs
>          // .NetCore 3.1 cannot stream data, looks like this will be possible in .Net 5.0.0
What about this?

2022-01-11 16:14 UTC, washibana requested changes

2022-01-11 16:14 UTC, washibana commented on backend/Origam.ServerCore/Attributes/DecodeQueryParameterAttribute.cs
> +﻿using System.Net;
There's missing license info.

2022-01-13 09:55 UTC, JindrichSusen commented on backend/Origam.ServerCore/Controller/SearchController.cs
>          // .NetCore 3.1 cannot stream data, looks like this will be possible in .Net 5.0.0
crete a new issue?

2022-01-13 10:01 UTC, washibana approved these changes

2022-01-13 10:39 UTC, merged