FIX: Server crashed after error in workflow
origam/origam pull request #2107
Opened 2023-10-26 11:19 UTC by JindrichSusen

the exception is still logged and the error is displayed to the user after removing the throw statement.

2023-11-02 08:21 UTC, washibana commented
Waiting for the implementation of tests.

2023-11-27 08:59 UTC, tvavrda requested changes
Please move the test workflows to a menu instead of action button menu.

2023-12-05 15:46 UTC, tvavrda approved these changes

2023-12-07 07:46 UTC, washibana approved these changes

2023-12-07 07:48 UTC, merged