FEATURE: Column order changing in Column configuration dialog (2023.1)
origam/origam pull request #2121
Opened 2023-10-31 05:11 UTC by ptomask

2023-10-31 19:35 UTC, tvavrda requested changes

2023-10-31 19:35 UTC, tvavrda commented on frontend-html/public/locale/localization_cs-CZ.json
@washibana can you provide translations in other languages?

2023-11-03 08:23 UTC, washibana commented on frontend-html/public/locale/localization_cs-CZ.json
Translations will be part of another PR.

2023-11-03 08:34 UTC, washibana requested changes

2023-11-03 08:34 UTC, washibana commented on frontend-html/src/gui/Components/Dialogs/ColumnsDialog.tsx
> +    const ord = this.temporaryPropertiesOrder;
Please use full words in the names of varialbles. `order`, `selectedIndex`.

2023-11-03 08:34 UTC, washibana commented on frontend-html/src/gui/Components/Dialogs/ColumnsDialog.tsx
> +  @action.bound handleOrderRowClick(id: any) {
It is better to know the meaning of `id`. E. g. `columnId`?

2023-11-03 09:31 UTC, washibana approved these changes

2023-11-03 09:33 UTC, washibana approved these changes

2023-11-03 15:46 UTC, tvavrda approved these changes

2023-11-03 15:48 UTC, merged