FIX: add forgotten locks to session store. It used to happen to execu…
origam/origam pull request #2231
Opened 2023-11-21 18:21 UTC by urbanekv

…te an action when long running UpdateObject was still processing. Without lock protection it led to unpredictable results.

2023-11-22 08:12 UTC, tvavrda requested changes

2023-11-22 08:12 UTC, tvavrda commented on backend/Origam.Server/Session Stores/WorkflowSessionStore.cs
> +                lock (_lock)
I would like to solve this for any `ExecuteAction` in any context store. I suggest to implement `ExecuteAction` in `SessionStore` with locking. And call `ExecuteActionInternal` which would be always locked then.

2023-11-23 07:29 UTC, tvavrda approved these changes

2023-11-23 08:33 UTC, washibana approved these changes

2023-11-23 08:33 UTC, merged