FIX: Date completion was failing when the custom format included month name (MMMM)
origam/origam pull request #2302
Opened 2023-12-12 12:22 UTC by JindrichSusen

2023-12-13 15:28 UTC, tvavrda requested changes

2023-12-13 15:28 UTC, tvavrda commented on frontend-html/src/tests/DateTimeCompleter.test.ts
> +const dateCompleterCz = new DateCompleter(DateSequence.DayMonthYear, ".",
Please add some more "CZ" tests that contain formats with separators, e.g. "9.12."

2023-12-14 09:19 UTC, tvavrda approved these changes

2023-12-15 07:13 UTC, washibana approved these changes

2023-12-15 07:13 UTC, merged