UX: Add bottom grid line border
origam/origam pull request #2447
Opened 2024-01-31 20:23 UTC by pilpadav

2024-02-01 08:44 UTC, JindrichSusen requested changes

2024-02-02 11:31 UTC, JindrichSusen requested changes

2024-02-02 11:31 UTC, JindrichSusen commented on frontend-html/src/gui/Components/ScreenElements/Table/TableRendering/cells/dataCell.ts
> +  ctx2d.strokeStyle = getComputedStyle(document.documentElement).getPropertyValue('--background4');
It should be enough to refer to the color like this: var(--background4)

2024-02-02 12:05 UTC, JindrichSusen approved these changes

2024-02-02 13:40 UTC, washibana approved these changes

2024-02-02 13:41 UTC, merged