CHG: This allows the application to receive any Unix signals sent to the container.
origam/origam pull request #2937
Opened 2024-11-14 21:05 UTC by JiriPrajz

2024-11-19 12:52 UTC, JindrichSusen requested changes

2024-11-19 12:52 UTC, JindrichSusen commented on docker/linux/startServer.sh
> -
So the startServer.sh does not start the server anymore. We should either:
- put "dotnet Origam.Server.dll" back
- rename the file
- get rid of it and put everything into entrypoint.sh

2024-11-21 08:20 UTC, JindrichSusen approved these changes
I've tested image origam/server:2024.12.alpha.3623.linux that shpould contain these changes. The server works in the linux container.

2024-11-26 09:59 UTC, washibana approved these changes

2024-11-26 10:01 UTC, merged