Prevent saving when rules fail
origam/origam pull request #47
Opened 2021-12-01 11:03 UTC by JindrichSusen

2021-12-01 11:07 UTC, tvavrda requested changes

2021-12-01 11:07 UTC, tvavrda commented on backend/Origam.ServerCore/Controller/UIServiceController.cs
> +                if (ruleExceptionData.Count > 0)
It should ignore "Low" severity issues. Only "High" should be counted and fail.

2021-12-01 16:54 UTC, tvavrda approved these changes

2021-12-03 09:10 UTC, washibana approved these changes

2021-12-03 09:11 UTC, merged