Azure ad multi tenant
origam/origam pull request #661
Opened 2022-06-24 14:33 UTC by washibana

2022-06-27 08:46 UTC, washibana commented
https://community.origam.com/t/azure-active-directory-login/1778

2022-06-28 10:21 UTC, tvavrda requested changes

2022-06-28 10:21 UTC, tvavrda commented on backend/Origam.Server/IdentityServerGui/Account/ExternalController.cs
> +                  ?? throw new Exception("Unknown userid");
The text of the exception should be more descriptive (what happened and what should be done to mitigate).

2022-06-28 12:23 UTC, tvavrda approved these changes

2022-06-28 12:28 UTC, merged