CHG: Introduced a possibility to aggregate content of single ZIP file…
origam/origam pull request #729
Opened 2022-07-20 21:24 UTC by tvavrda

…s instead of all the files in the directory.

Connection string of work queue file loader has been refactored and instead of "aggregate" boolean value it now uses a single "readType" property that can have the following values:
- SingleFiles: Default, loads each file separately
- AggregateCompressedFiles: Loads each compressed file separately and aggregates all files inside it
- AggregateAllFiles: Loads all the files available as a single queue entry, including all the files inside compressed files
- SplitByRows: Splits the files by each nth row specified using the "splitFileByRows" and "keepHeader" parameters

2022-07-25 07:03 UTC, washibana requested changes

2022-07-25 07:03 UTC, washibana commented on backend/Origam.Workflow/Strings.cs-CZ.resx
> -  <data name="ErrorUnknownAccessMode" xml:space="preserve">
This message should be in Czech.

2022-07-25 07:06 UTC, washibana commented
The documentation article needs to be updated: https://community.origam.com/t/work-queue-file-loader/784

2022-07-25 09:46 UTC, tvavrda commented on backend/Origam.Workflow/Strings.cs-CZ.resx
> -  <data name="ErrorUnknownAccessMode" xml:space="preserve">
This is a deleted part.

2023-05-17 14:49 UTC, tvavrda commented
Documentation has been updated.

2023-05-18 09:42 UTC, washibana approved these changes

2023-05-18 09:45 UTC, merged