Fix of Origam Architect for PostgresSql:
origam/origam pull request #730
Opened 2022-07-25 09:35 UTC by davidpochobradsky

1. Postgresql => Create New Project on PostgresSQL database terminated in ERROR:

https://community.origam.com/t/origam-architect-create-new-project-with-postgressql-database-fail-on-missing-system-numeric-vectors-dll/1735/6

    * By fixing this issue, I have found on my local postgresql installation that user <dbname> which has been created by installation is not removed in case if the create new project fails (rollback didn't work because in my database there was no user postgres). I fixed this by updating a script for rollback.

2. Postges + MS SQL:

    * New project could not be created because of failing step **Create new Web User** => there was remove of column `IsLockedOut` column in the model but this column remained in `CreateOrigamUserInsert` in both adapters - MS SQL and Postgres

Note:

I included powershell script for local wix testing => build-msi.ps1 and build-msi.bat to run it with specific parameters.

2022-07-26 08:23 UTC, washibana requested changes
Please remove all the comments, the information is available from pull request and commit message.

2022-07-26 09:03 UTC, davidpochobradsky commented
@washibana - All comments are removed except one line in PgSqlDataService. There used to be a comment so I left there a line to explain why the command `Reassign owned by` is there. Is it ok?

2022-07-26 09:23 UTC, washibana approved these changes

2022-07-27 11:17 UTC, JiriPrajz approved these changes

2022-07-28 08:55 UTC, merged