Rule engine refactoring
origam/origam pull request #773
Opened 2022-08-04 13:32 UTC by JindrichSusen

2022-08-07 08:12 UTC, tvavrda requested changes

2022-08-07 08:12 UTC, tvavrda commented on backend/Origam.Schema.EntityModel/XsltFunctionSchemaItemProvider.cs
> +        public override AbstractSchemaItem NewItem(Type type, Guid schemaExtensionId, SchemaItemGroup group)
You may ommit `NewItem` and `NewItemTypes` methods by adding `this.ChildItemTypes.Add(typeof(XsltFunctionCollection))` to the constructor.

See `AbstractWorkflowBlock` for an example.

2022-08-08 09:23 UTC, washibana requested changes

2022-08-08 09:23 UTC, washibana commented on backend/Origam.Workbench.Services/CoreServices/DataServiceFactory.cs
> +﻿#region license
This is a new file, so license years should reflect this year (2022).

2022-08-08 09:23 UTC, washibana commented on backend/Origam.Workbench.Services/CoreServices/ICoreDataService.cs
> +﻿using System;
Missing license information.

2022-08-08 09:23 UTC, washibana commented on backend/Origam.Workflow/Origam.Workflow.csproj
> +    <Compile Remove="NullStateMachineService.cs" />
Please review the necessity of the instruction.

2022-08-08 09:50 UTC, washibana commented
@JindrichSusen We also need an article on support for external collections of XSLT functions.

2022-08-11 07:59 UTC, washibana approved these changes

2022-08-11 08:11 UTC, merged