Lazy work queues
origam/origam pull request #813
Opened 2022-08-16 14:54 UTC by JindrichSusen

2022-08-17 07:45 UTC, washibana requested changes

2022-08-17 07:45 UTC, washibana commented on backend/Origam.OrigamEngine/ModelXmlBuilders/FormXmlBuilder.cs
> +					// if (c.ColumnName == "Data")
Please remove commented code.

2022-08-17 07:45 UTC, washibana commented on backend/Origam.Server/Controller/UIServiceController.cs
> +        private readonly string workQueueEntity = "WorkQueueEntry";
Properties should be declared at the beginning of the class.

2022-08-17 07:45 UTC, washibana commented on frontend-html/src/model/entities/DataViewLifecycle/DataViewLifecycle.ts
> +      // console.log("getSelectedRowId: "+  getSelectedRowId(this));
Please remove commented code.

2022-08-18 13:05 UTC, tvavrda commented on backend/Origam.Server/Controller/UIServiceController.cs
> +            if (sessionStore is WorkQueueSessionStore workQueueSessionStore)
Wouldn't it be right to encapsulate this into the SessionStore class so that the controller stays clean from these decisions?

2022-08-22 19:30 UTC, washibana approved these changes

2022-08-22 19:31 UTC, merged